Description of loadtpl
Home > m2html > @template > private > loadtpl.m
loadtpl
PURPOSE
TEMPLATE/LOADTPL Read a template from file
SYNOPSIS
function tpl = loadtpl(tpl,handle)
DESCRIPTION
TEMPLATE/LOADTPL Read a template from file
  TPL = LOADTPL(TPL,HANDLE) read the template file associated with the
  handle HANDLE in the template TPL and store it in the variable HANDLE.
CROSS-REFERENCE INFORMATION
This function calls:
get TEMPLATE/GET Access data stored in a Template object
set TEMPLATE/SET Edit data stored in a Template object
This function is called by:
get TEMPLATE/GET Access data stored in a Template object
subst TEMPLATE/SUBST Substitute a replacement field by its value
set TEMPLATE/SET Edit data stored in a Template object
SOURCE CODE
function tpl = loadtpl(tpl,handle)
%TEMPLATE/LOADTPL Read a template from file
%  TPL = LOADTPL(TPL,HANDLE) read the template file associated with the
%  handle HANDLE in the template TPL and store it in the variable HANDLE.
%  Copyright (C) 2003 Guillaume Flandin <Guillaume@artefact.tk>
%  $Revision: 1.0 $Date: 2003/05/05 22:19:51 $
if ~isempty(get(tpl,'var',handle))
    return;
else
    ind = find(ismember(tpl.handles,handle));
    if isempty(ind)
        error('[Template] No such template handle.');
    else
        filename = tpl.file{ind};
        [fid, errmsg] = fopen(filename,'rt');
        if ~isempty(errmsg)
            error(sprintf('Cannot open template file %s.',filename));
        end
        tpl = set(tpl,'var',handle,fscanf(fid,'%c'));
        fclose(fid);
    end
end