Description of m2html
Home > m2html > m2html.m
m2html
PURPOSE
M2HTML - Documentation Generator for Matlab M-files and Toolboxes in HTML
SYNOPSIS
function m2html(varargin)
DESCRIPTION
M2HTML - Documentation Generator for Matlab M-files and Toolboxes in HTML
  M2HTML by itself generates an HTML documentation of the Matlab M-files found
  in the direct subdirectories of the current directory. HTML files are
  written in a 'doc' directory (created if necessary). All the others options
  are set to default (in brackets in the following).
  M2HTML('PropertyName1',PropertyValue1,'PropertyName2',PropertyValue2,...)
  sets multiple option values. The list of option names and default values is:
    o mFiles - Cell array of strings or character array containing the
       list of M-files and/or directories of M-files for which an HTML
       documentation will be built (use relative paths without backtracking).
       Launch M2HTML one directory above the directory your wanting to
       generate documentation for  [ <all direct subdirectories> ]
    o htmlDir - Top level directory for generated HTML files [ 'doc' ]
    o recursive - Process subdirectories recursively [ on | {off} ]
    o source - Include Matlab source code in the generated documentation
                               [ {on} | off ]
    o download - Add a link to download each M-file separately [ on | {off} ]
    o syntaxHighlighting - Source Code Syntax Highlighting [ {on} | off ]
    o tabs - Replace '\t' (horizontal tab) in source code by n white space
        characters [ 0 ... {4} ... n ]
    o globalHypertextLinks - Hypertext links among separate Matlab
        directories [ on | {off} ]
    o todo - Create a TODO list in each directory summarizing all the
        '% TODO %' lines found in Matlab code [ on | {off}]
    o graph - Compute a dependency graph using GraphViz [ on | {off}]
        'dot' required, see <http://www.graphviz.org/>
    o indexFile - Basename of the HTML index file [ 'index' ]
    o extension - Extension of generated HTML files [ '.html' ]
    o template - HTML template name to use [ {'blue'} | 'frame' | ... ]
    o search - Add a PHP search engine [ on | {off}] - beta version!
    o ignoredDir - List of directories to be ignored [ {'.svn','.git','.github','.hg'} ]
    o save - Save current state after M-files parsing in 'm2html.mat'
        in directory htmlDir [ on | {off}]
    o load - Load a previously saved '.mat' M2HTML state to generate HTML
        files once again with possibly other options [ <none> ]
    o verbose - Verbose mode [ {on} | off ]
  For more information, please read the M2HTML tutorial and FAQ at:
    <http://www.artefact.tk/software/matlab/m2html/>
  Examples:
    >> m2html('mfiles','matlab', 'htmldir','doc');
    >> m2html('mfiles',{'matlab/signal' 'matlab/image'}, 'htmldir','doc');
    >> m2html('mfiles','matlab', 'htmldir','doc', 'recursive','on');
    >> m2html('mfiles','mytoolbox', 'htmldir','doc', 'source','off');
    >> m2html('mfiles','matlab', 'htmldir','doc', 'global','on');
    >> m2html( ... , 'template','frame', 'index','menu');
CROSS-REFERENCE INFORMATION
This function calls:
get TEMPLATE/GET Access data stored in a Template object
parse TEMPLATE/PARSE Fill in replacement fields with the class properties
set TEMPLATE/SET Edit data stored in a Template object
template TEMPLATE HTML Template Toolbox Constructor
doxywrite DOXYWRITE Write a 'search.idx' file compatible with DOXYGEN
mdot MDOT - Export a dependency graph into DOT language
mexexts List of MEX files extensions
mfileparse MFILEPARSE Parsing of an M-file to obtain synopsis, help and references
openfile OPENFILE Open a file in read/write mode, catching errors
searchindex SEARCHINDEX Compute keywords statistics of an M-file
splitcode SPLITCODE Split a line of Matlab code in string, comment and other
strtok2 Modified version of STRTOK to also return the quotient
This function is called by:
SUBFUNCTIONS
function mfiles = getmfiles(mdirs, mfiles, recursive,ignoredDir)
function calldot(dotexec, mdotfile, mapfile, pngfile, opt)
function s = backtomaster(mdir)
function ldir = splitpath(p)
function name = extractname(synopsis)
function f = fullurl(varargin)
function str = escapeblank(str)
function str = entity(str)
function str = horztab(str,n)
SOURCE CODE
function m2html(varargin)
%M2HTML - Documentation Generator for Matlab M-files and Toolboxes in HTML
%  M2HTML by itself generates an HTML documentation of the Matlab M-files found
%  in the direct subdirectories of the current directory. HTML files are
%  written in a 'doc' directory (created if necessary). All the others options
%  are set to default (in brackets in the following).
%  M2HTML('PropertyName1',PropertyValue1,'PropertyName2',PropertyValue2,...)
%  sets multiple option values. The list of option names and default values is:
%    o mFiles - Cell array of strings or character array containing the
%       list of M-files and/or directories of M-files for which an HTML
%       documentation will be built (use relative paths without backtracking).
%       Launch M2HTML one directory above the directory your wanting to
%       generate documentation for  [ <all direct subdirectories> ]
%    o htmlDir - Top level directory for generated HTML files [ 'doc' ]
%    o recursive - Process subdirectories recursively [ on | {off} ]
%    o source - Include Matlab source code in the generated documentation
%                               [ {on} | off ]
%    o download - Add a link to download each M-file separately [ on | {off} ]
%    o syntaxHighlighting - Source Code Syntax Highlighting [ {on} | off ]
%    o tabs - Replace '\t' (horizontal tab) in source code by n white space
%        characters [ 0 ... {4} ... n ]
%    o globalHypertextLinks - Hypertext links among separate Matlab
%        directories [ on | {off} ]
%    o todo - Create a TODO list in each directory summarizing all the
%        '% TODO %' lines found in Matlab code [ on | {off}]
%    o graph - Compute a dependency graph using GraphViz [ on | {off}]
%        'dot' required, see <http://www.graphviz.org/>
%    o indexFile - Basename of the HTML index file [ 'index' ]
%    o extension - Extension of generated HTML files [ '.html' ]
%    o template - HTML template name to use [ {'blue'} | 'frame' | ... ]
%    o search - Add a PHP search engine [ on | {off}] - beta version!
%    o ignoredDir - List of directories to be ignored [ {'.svn','.git','.github','.hg'} ]
%    o save - Save current state after M-files parsing in 'm2html.mat'
%        in directory htmlDir [ on | {off}]
%    o load - Load a previously saved '.mat' M2HTML state to generate HTML
%        files once again with possibly other options [ <none> ]
%    o verbose - Verbose mode [ {on} | off ]
%
%  For more information, please read the M2HTML tutorial and FAQ at:
%    <http://www.artefact.tk/software/matlab/m2html/>
%
%  Examples:
%    >> m2html('mfiles','matlab', 'htmldir','doc');
%    >> m2html('mfiles',{'matlab/signal' 'matlab/image'}, 'htmldir','doc');
%    >> m2html('mfiles','matlab', 'htmldir','doc', 'recursive','on');
%    >> m2html('mfiles','mytoolbox', 'htmldir','doc', 'source','off');
%    >> m2html('mfiles','matlab', 'htmldir','doc', 'global','on');
%    >> m2html(... , 'template','frame', 'index','menu');
%  Copyright (C) 2005 Guillaume Flandin <Guillaume@artefact.tk>
%  $Revision: 1.5 $Date: 2005/05/01 16:15:30 $
%  This program is free software; you can redistribute it and/or
%  modify it under the terms of the GNU General Public License
%  as published by the Free Software Foundation; either version 2
%  of the License, or any later version.
%
%  This program is distributed in the hope that it will be useful,
%  but WITHOUT ANY WARRANTY; without even the implied warranty of
%  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%  GNU General Public License for more details.
%
%  You should have received a copy of the GNU General Public License
%  along with this program; if not, write to the Free Software
%  Foundation Inc, 59 Temple Pl. - Suite 330, Boston, MA 02111-1307, USA.
%  Suggestions for improvement and fixes are always welcome, although no
%  guarantee is made whether and when they will be implemented.
%  Send requests to <Guillaume@artefact.tk>
%  For tips on how to write Matlab code, see:
%     * MATLAB Programming Style Guidelines, by R. Johnson:
%       <http://www.datatool.com/prod02.htm>
%     * For tips on creating help for your m-files 'type help.m'.
%     * Matlab documentation on M-file Programming:
%  <http://www.mathworks.com/access/helpdesk/help/techdoc/matlab_prog/ch_funh8.html>
%  This function uses the Template class so that you can fully customize
%  the output. You can modify .tpl files in templates/blue/ or create new
%  templates in a new directory.
%  See the template class documentation for more details.
%  <http://www.artefact.tk/software/matlab/template/>
%  Latest information on M2HTML is available on the web through:
%  <http://www.artefact.tk/software/matlab/m2html/>
%  Other Matlab to HTML converters available on the web:
%  1/ mat2html.pl, J.C. Kantor, in Perl, 1995:
%     <http://fresh.t-systems-sfr.com/unix/src/www/mat2html>
%  2/ htmltools, B. Alsberg, in Matlab, 1997:
%     <http://www.mathworks.com/matlabcentral/fileexchange/loadFile.do?objectId=175>
%  3/ mtree2html2001, H. Pohlheim, in Perl, 1996, 2001:
%     <http://www.pohlheim.com/perl_main.html#matlabdocu>
%  4/ MatlabCodeColorizer, S. Faridani, in C#, 2005:
%     <http://www.pitchup.com/matlabcolorizer/>
%  5/ Highlight, G. Flandin, in Matlab, 2003:
%     <http://www.artefact.tk/software/matlab/highlight/>
%  6/ mdoc, P. Brinkmann, in Matlab, 2003:
%     <http://www.math.uiuc.edu/~brinkman/software/mdoc/>
%  7/ Ocamaweb, Miriad Technologies, in Ocaml, 2002:
%     <http://ocamaweb.sourceforge.net/>
%  8/ Matdoc, M. Kaminsky, in Perl, 2003:
%     <http://www.mathworks.com/matlabcentral/fileexchange/loadFile.do?objectId=3498>
%  9/ Matlab itself, The Mathworks Inc, with HELPWIN, DOC and PUBLISH (R14)
%--------------------------------------------------------------------------
%- Set up options and default parameters
%--------------------------------------------------------------------------
t0 = clock; % for statistics
msgInvalidPair = 'Bad value for argument: ''%s''';
options = struct('verbose', 1,...
                 'mFiles', {{'.'}},...
                 'htmlDir', 'doc',...
                 'recursive', 0,...
                 'source', 1,...
                 'download',0,...
                 'syntaxHighlighting', 1,...
                 'tabs', 4,...
                 'globalHypertextLinks', 0,...
                 'graph', 0,...
                 'todo', 0,...
                 'load', 0,...
                 'save', 0,...
                 'search', 0,...
                 'helptocxml', 0,...
                 'indexFile', 'index',...
                 'extension', '.html',...
                 'template', 'blue',...
                 'rootdir', pwd,...
                 'ignoredDir', {{'.svn','.git','.github','.hg'}}, ...
                 'language', 'english');
if nargin == 1 && isstruct(varargin{1})
    paramlist = [ fieldnames(varargin{1}) ...
                  struct2cell(varargin{1}) ]';
    paramlist = { paramlist{:} };
else
    if mod(nargin,2)
        error('Invalid parameter/value pair arguments.');
    end
    paramlist = varargin;
end
optionsnames = lower(fieldnames(options));
for i=1:2:length(paramlist)
    pname = paramlist{i};
    pvalue = paramlist{i+1};
    ind = strmatch(lower(pname),optionsnames);
    if isempty(ind)
        error(['Invalid parameter: ''' pname '''.']);
    elseif length(ind) > 1
        error(['Ambiguous parameter: ''' pname '''.']);
    end
    switch(optionsnames{ind})
        case 'verbose'
            if strcmpi(pvalue,'on')
                options.verbose = 1;
            elseif strcmpi(pvalue,'off')
                options.verbose = 0;
            else
                error(sprintf(msgInvalidPair,pname));
            end
        case 'mfiles'
            if iscellstr(pvalue)
                options.mFiles = pvalue;
            elseif ischar(pvalue)
                options.mFiles = cellstr(pvalue);
            else
                error(sprintf(msgInvalidPair,pname));
            end
            options.load = 0;
        case 'htmldir'
            if ischar(pvalue)
                if isempty(pvalue)
                    options.htmlDir = '.';
                else
                    options.htmlDir = pvalue;
                end
            else
                error(sprintf(msgInvalidPair,pname));
            end
        case 'recursive'
            if strcmpi(pvalue,'on')
                options.recursive = 1;
            elseif strcmpi(pvalue,'off')
                options.recursive = 0;
            else
                error(sprintf(msgInvalidPair,pname));
            end
            options.load = 0;
        case 'source'
            if strcmpi(pvalue,'on')
                options.source = 1;
            elseif strcmpi(pvalue,'off')
                options.source = 0;
            else
                error(sprintf(msgInvalidPair,pname));
            end
        case 'download'
            if strcmpi(pvalue,'on')
                options.download = 1;
            elseif strcmpi(pvalue,'off')
                options.download = 0;
            else
                error(sprintf(msgInvalidPair,pname));
            end
        case 'syntaxhighlighting'
            if strcmpi(pvalue,'on')
                options.syntaxHighlighting = 1;
            elseif strcmpi(pvalue,'off')
                options.syntaxHighlighting = 0;
            else
                error(sprintf(msgInvalidPair,pname));
            end
        case 'tabs'
            if pvalue >= 0
                options.tabs = pvalue;
            else
                error(sprintf(msgInvalidPair,pname));
            end
        case 'globalhypertextlinks'
            if strcmpi(pvalue,'on')
                options.globalHypertextLinks = 1;
            elseif strcmpi(pvalue,'off')
                options.globalHypertextLinks = 0;
            else
                error(sprintf(msgInvalidPair,pname));
            end
            options.load = 0;
        case 'graph'
            if strcmpi(pvalue,'on')
                options.graph = 1;
            elseif strcmpi(pvalue,'off')
                options.graph = 0;
            else
                error(sprintf(msgInvalidPair,pname));
            end
        case 'todo'
            if strcmpi(pvalue,'on')
                options.todo = 1;
            elseif strcmpi(pvalue,'off')
                options.todo = 0;
            else
                error(sprintf(msgInvalidPair,pname));
            end
        case 'load'
            if ischar(pvalue)
                if exist(pvalue) == 7 % directory provided
                    pvalue = fullfile(pvalue,'m2html.mat');
                end
                try
                    load(pvalue);
                catch
                    error(sprintf('Unable to load %s.', pvalue));
                end
                options.load = 1;
                [dummy options.template] = fileparts(options.template);
            else
                error(sprintf(msgInvalidPair,pname));
            end
        case 'save'
            if strcmpi(pvalue,'on')
                options.save = 1;
            elseif strcmpi(pvalue,'off')
                options.save = 0;
            else
                error(sprintf(msgInvalidPair,pname));
            end
        case 'search'
            if strcmpi(pvalue,'on')
                options.search = 1;
            elseif strcmpi(pvalue,'off')
                options.search = 0;
            else
                error(sprintf(msgInvalidPair,pname));
            end
        case 'helptocxml'
            if strcmpi(pvalue,'on')
                options.helptocxml = 1;
            elseif strcmpi(pvalue,'off')
                options.helptocxml = 0;
            else
                error(sprintf(msgInvalidPair,pname));
            end
        case 'indexfile'
            if ischar(pvalue)
                options.indexFile = pvalue;
            else
                error(sprintf(msgInvalidPair,pname));
            end
        case 'extension'
            if ischar(pvalue) && pvalue(1) == '.'
                options.extension = pvalue;
            else
                error(sprintf(msgInvalidPair,pname));
            end
        case 'template'
            if ischar(pvalue)
                options.template = pvalue;
            else
                error(sprintf(msgInvalidPair,pname));
            end
        case 'ignoreddir'
            if iscellstr(pvalue)
                options.ignoredDir = pvalue;
            elseif ischar(pvalue)
                options.ignoredDir = cellstr(pvalue);
            else
                error(sprintf(msgInvalidPair,pname));
            end
        case 'language'
            if ischar(pvalue)
                options.language = pvalue;
            else
                error(sprintf(msgInvalidPair,pname));
            end
        otherwise
            error(['Invalid parameter: ''' pname '''.']);
    end
end
%--------------------------------------------------------------------------
%- Get template files location
%--------------------------------------------------------------------------
s = fileparts(which(mfilename));
options.template = fullfile(s,'templates',options.template);
if exist(options.template) ~= 7
    error('[Template] Unknown template.');
end
%--------------------------------------------------------------------------
%- Get list of M-files
%--------------------------------------------------------------------------
if ~options.load
    if strcmp(options.mFiles,'.')
        d = dir(pwd); d = {d([d.isdir]).name};
        options.mFiles = {d{~ismember(d,{'.' '..' options.ignoredDir{:}})}};
    end
    mfiles = getmfiles(options.mFiles,{},options.recursive,options.ignoredDir);
    if ~length(mfiles), fprintf('Nothing to be done.\n'); return; end
    if options.verbose
        fprintf('Found %d M-files.\n',length(mfiles));
    end
    mfiles = sort(mfiles); % sort list of M-files in dictionary order
end
%--------------------------------------------------------------------------
%- Get list of (unique) directories and (unique) names
%--------------------------------------------------------------------------
if ~options.load
    mdirs = {};
    names = {};
    for i=1:length(mfiles)
        [mdirs{i}, names{i}] = fileparts(mfiles{i});
        if isempty(mdirs{i}), mdirs{i} = '.'; end
    end
    mdir = unique(mdirs);
    if options.verbose
        fprintf('Found %d unique Matlab directories.\n',length(mdir));
    end
    name = names;
    %name = unique(names); % output is sorted
    %if options.verbose,
    %    fprintf('Found %d unique Matlab files.\n',length(name));
    %end
end
%--------------------------------------------------------------------------
%- Create output directory, if necessary
%--------------------------------------------------------------------------
if isempty(dir(options.htmlDir))
    %- Create the top level output directory
    if options.verbose
        fprintf('Creating directory %s...\n',options.htmlDir);
    end
    if options.htmlDir(end) == filesep
        options.htmlDir(end) = [];
    end
    [pathdir, namedir] = fileparts(options.htmlDir);
    if isempty(pathdir)
        [status, msg] = mkdir(escapeblank(namedir));
    else
        [status, msg] = mkdir(escapeblank(pathdir), escapeblank(namedir));
    end
    if ~status, error(msg); end
end
%--------------------------------------------------------------------------
%- Get synopsis, H1 line, script/function, subroutines, cross-references, todo
%--------------------------------------------------------------------------
if ~options.load
    synopsis   = cell(size(mfiles));
    h1line     = cell(size(mfiles));
    subroutine = cell(size(mfiles));
    hrefs      = sparse(length(mfiles), length(mfiles));
    todo       = struct('mfile',[], 'line',[], 'comment',{{}});
    ismex      = zeros(length(mfiles), numel(mexexts));
    statlist   = {};
    statinfo   = sparse(1,length(mfiles));
    kw         = cell(size(mfiles));
    freq       = cell(size(mfiles));
    for i=1:length(mfiles)
        if options.verbose
            fprintf('Processing file %s...',mfiles{i});
        end
        s = mfileparse(mfiles{i}, mdirs, names, options);
        synopsis{i}   = s.synopsis;
        h1line{i}     = s.h1line;
        subroutine{i} = s.subroutine;
        hrefs(i,:)    = s.hrefs;
        todo.mfile    = [todo.mfile repmat(i,1,length(s.todo.line))];
        todo.line     = [todo.line s.todo.line];
        todo.comment  = {todo.comment{:} s.todo.comment{:}};
        ismex(i,:)    = s.ismex;
        if options.search
            if options.verbose, fprintf('search...'); end
            [kw{i}, freq{i}] = searchindex(mfiles{i});
            statlist = union(statlist, kw{i});
        end
        if options.verbose, fprintf('\n'); end
    end
    hrefs = hrefs > 0;
    if options.search
        if options.verbose
            fprintf('Creating the search index...');
        end
        statinfo = sparse(length(statlist),length(mfiles));
        for i=1:length(mfiles)
            i1 = find(ismember(statlist, kw{i}));
            i2 = repmat(i,1,length(i1));
            if ~isempty(i1)
                statinfo(sub2ind(size(statinfo),i1,i2)) = freq{i};
            end
            if options.verbose, fprintf('.'); end
        end
        clear kw freq;
        if options.verbose, fprintf('\n'); end
    end
end
%--------------------------------------------------------------------------
%- Save M-filenames and cross-references for further analysis
%--------------------------------------------------------------------------
matfilesave = 'm2html.mat';
if options.save
    if options.verbose
        fprintf('Saving MAT file %s...\n',matfilesave);
    end
    save(fullfile(options.htmlDir,matfilesave), ...
        'mfiles', 'names', 'mdirs', 'name', 'mdir', 'options', ...
        'hrefs', 'synopsis', 'h1line', 'subroutine', 'todo', 'ismex', ...
        'statlist', 'statinfo');
end
%--------------------------------------------------------------------------
%- Setup the output directories
%--------------------------------------------------------------------------
for i=1:length(mdir)
    if exist(fullfile(options.htmlDir,mdir{i})) ~= 7
        ldir = splitpath(mdir{i});
        for j=1:length(ldir)
            if exist(fullfile(options.htmlDir,ldir{1:j})) ~= 7
                %- Create the output directory
                if options.verbose
                    fprintf('Creating directory %s...\n',...
                            fullfile(options.htmlDir,ldir{1:j}));
                end
                if j == 1
                    [status, msg] = mkdir(escapeblank(options.htmlDir), ...
                        escapeblank(ldir{1}));
                else
                    [status, msg] = mkdir(escapeblank(options.htmlDir), ...
                        escapeblank(fullfile(ldir{1:j})));
                end
                error(msg);
            end
        end
    end
end
%--------------------------------------------------------------------------
%- Write the master index file
%--------------------------------------------------------------------------
tpl_master = 'master.tpl';
tpl_master_identifier_nbyline = 4;
php_search = 'search.php';
dotbase = 'graph';
%- Create the HTML template
tpl = template(options.template,'remove');
tpl = set(tpl,'file','TPL_MASTER',tpl_master);
tpl = set(tpl,'block','TPL_MASTER','rowdir','rowdirs');
tpl = set(tpl,'block','TPL_MASTER','idrow','idrows');
tpl = set(tpl,'block','idrow','idcolumn','idcolumns');
tpl = set(tpl,'block','TPL_MASTER','search','searchs');
tpl = set(tpl,'block','TPL_MASTER','graph','graphs');
%- Open for writing the HTML master index file
curfile = fullfile(options.htmlDir,[options.indexFile options.extension]);
if options.verbose
    fprintf('Creating HTML file %s...\n',curfile);
end
fid = openfile(curfile,'w');
%- Set some template variables
tpl = set(tpl,'var','DATE',[datestr(now,8) ' ' datestr(now,1) ' ' ...
                            datestr(now,13)]);
tpl = set(tpl,'var','MASTERPATH', './');
tpl = set(tpl,'var','DIRS', sprintf('%s ',mdir{:}));
%- Print list of unique directories
for i=1:length(mdir)
    tpl = set(tpl,'var','L_DIR',...
              fullurl(mdir{i},[options.indexFile options.extension]));
    tpl = set(tpl,'var','DIR',mdir{i});
    tpl = parse(tpl,'rowdirs','rowdir',1);
end
%- Print full list of M-files (sorted by column)
[sortnames, ind] = sort(names);
m_mod = mod(length(sortnames), tpl_master_identifier_nbyline);
ind = [ind zeros(1,tpl_master_identifier_nbyline-m_mod)];
m_floor = floor(length(ind) / tpl_master_identifier_nbyline);
ind = reshape(ind,m_floor,tpl_master_identifier_nbyline)';
for i=1:prod(size(ind))
    if ind(i)
        tpl = set(tpl,'var','L_IDNAME',...
            fullurl(mdirs{ind(i)},[names{ind(i)} options.extension]));
        tpl = set(tpl,'var','T_IDNAME',mdirs{ind(i)});
        tpl = set(tpl,'var','IDNAME',names{ind(i)});
        tpl = parse(tpl,'idcolumns','idcolumn',1);
    else
        tpl = set(tpl,'var','L_IDNAME','');
        tpl = set(tpl,'var','T_IDNAME','');
        tpl = set(tpl,'var','IDNAME','');
        tpl = parse(tpl,'idcolumns','idcolumn',1);
    end
    if mod(i,tpl_master_identifier_nbyline) == 0
        tpl = parse(tpl,'idrows','idrow',1);
        tpl = set(tpl,'var','idcolumns','');
    end
end
%- Add a search form if necessary
tpl = set(tpl,'var','searchs','');
if options.search
    tpl = set(tpl,'var','PHPFILE',php_search);
    tpl = parse(tpl,'searchs','search',1);
end
%- Link to a full dependency graph, if necessary
tpl = set(tpl,'var','graphs','');
if options.graph && options.globalHypertextLinks && length(mdir) > 1
    tpl = set(tpl,'var','LGRAPH',[dotbase options.extension]);
    tpl = parse(tpl,'graphs','graph',1);
end
%- Print the template in the HTML file
tpl = parse(tpl,'OUT','TPL_MASTER');
fprintf(fid,'%s',get(tpl,'OUT'));
fclose(fid);
%--------------------------------------------------------------------------
%- Copy template files (CSS, images, ...)
%--------------------------------------------------------------------------
% Get list of files
d = dir(options.template);
d = {d(~[d.isdir]).name};
% Copy files
for i=1:length(d)
    [p, n, ext] = fileparts(d{i});
    if ~strcmp(ext,'.tpl') ... % do not copy .tpl files
       && ~strcmp([n ext],'Thumbs.db') % do not copy this Windows generated file
        if isempty(dir(fullfile(options.htmlDir,d{i})))
            if options.verbose
                fprintf('Copying template file %s...\n',d{i});
            end
            %- there is a bug with <copyfile> in Matlab 6.5 :
            %   http://www.mathworks.com/support/solutions/data/1-1B5JY.html
            %- and <copyfile> does not overwrite files even if newer...
            [status, errmsg] = copyfile(fullfile(options.template,d{i}),...
                                        options.htmlDir);
            %- If you encounter this bug, please uncomment one of the following lines
            % eval(['!cp -rf ' fullfile(options.template,d{i}) ' ' options.htmlDir]);
            % eval(['!copy ' fullfile(options.template,d{i}) ' ' options.htmlDir]);
            % status = 1;
            if ~status
                if ~isempty(errmsg)
                    error(errmsg)
                else
                    warning(sprintf(['<copyfile> failed to do its job...\n' ...
                'This is a known bug in Matlab 6.5 (R13).\n' ...
                'See http://www.mathworks.com/support/solutions/data/1-1B5JY.html']));
                end
            end
        end
    end
end
%--------------------------------------------------------------------------
%- Search engine (index file and PHP script)
%--------------------------------------------------------------------------
tpl_search = 'search.tpl';
idx_search = 'search.idx';
% TODO % improving the fill in of 'statlist' and 'statinfo'
% TODO % improving the search template file and update the CSS file
if options.search
    %- Write the search index file in output directory
    if options.verbose
        fprintf('Creating Search Index file %s...\n', idx_search);
    end
    docinfo = cell(length(mfiles),2);
    for i=1:length(mfiles)
        docinfo{i,1} = h1line{i};
        docinfo{i,2} = fullurl(mdirs{i}, [names{i} options.extension]);
    end
    doxywrite(fullfile(options.htmlDir,idx_search),statlist,statinfo,docinfo);
    %- Create the PHP template
    tpl = template(options.template,'remove');
    tpl = set(tpl,'file','TPL_SEARCH',tpl_search);
    %- Open for writing the PHP search script
    curfile = fullfile(options.htmlDir, php_search);
    if options.verbose
        fprintf('Creating PHP script %s...\n',curfile);
    end
    fid = openfile(curfile,'w');
    %- Set template fields
    tpl = set(tpl,'var','INDEX',[options.indexFile options.extension]);
    tpl = set(tpl,'var','MASTERPATH','./');
    tpl = set(tpl,'var','DATE',[datestr(now,8) ' ' datestr(now,1) ' ' ...
                                datestr(now,13)]);
    tpl = set(tpl,'var','IDXFILE',idx_search);
    tpl = set(tpl,'var','PHPFILE',php_search);
    %- Print the template in the HTML file
    tpl = parse(tpl,'OUT','TPL_SEARCH');
    fprintf(fid,'%s',get(tpl,'OUT'));
    fclose(fid);
end
%--------------------------------------------------------------------------
%- Create <helptoc.xml> needed to display hierarchical entries in Contents panel
%--------------------------------------------------------------------------
% See http://www.mathworks.com/access/helpdesk/help/techdoc/matlab_env/guiref16.html
% and http://www.mathworks.com/support/solutions/data/1-18U6Q.html?solution=1-18U6Q
% TODO % display directories in TOC hierarchically instead of linearly
if options.helptocxml
    curfile = fullfile(options.htmlDir, 'helptoc.xml');
    if options.verbose
        fprintf('Creating XML Table-Of-Content %s...\n',curfile);
    end
    fid = openfile(curfile,'w');
    fprintf(fid,'<?xml version=''1.0'' encoding=''ISO-8859-1'' ?>\n');
    fprintf(fid,'<!-- $Date: %s $ -->\n\n', datestr(now,31));
    fprintf(fid,'<toc version="1.0">\n\n');
    fprintf(fid,['<tocitem target="%s" ',...
        'image="$toolbox/matlab/icons/book_mat.gif">%s\n'], ...
        [options.indexFile options.extension],'Toolbox');
    for i=1:length(mdir)
        fprintf(fid,['<tocitem target="%s" ',...
            'image="$toolbox/matlab/icons/reficon.gif">%s\n'], ...
            fullfile(mdir{i}, ...
                [options.indexFile options.extension]),mdir{i});
        if options.graph
            fprintf(fid,['\t<tocitem target="%s" ',...
            'image="$toolbox/matlab/icons/simulinkicon.gif">%s</tocitem>\n'], ...
                fullfile(mdir{i},...
                [dotbase options.extension]),'Dependency Graph');
        end
        if options.todo
            if ~isempty(intersect(find(strcmp(mdir{i},mdirs)),todo.mfile))
                fprintf(fid,['\t<tocitem target="%s" ',...
                'image="$toolbox/matlab/icons/demoicon.gif">%s</tocitem>\n'], ...
                    fullfile(mdir{i},...
                    ['todo' options.extension]),'Todo list');
            end
        end
        for j=1:length(mdirs)
            if strcmp(mdirs{j},mdir{i})
                curfile = fullfile(mdir{i},...
                    [names{j} options.extension]);
                fprintf(fid,'\t<tocitem target="%s">%s</tocitem>\n', ...
                    curfile,names{j});
            end
        end
        fprintf(fid,'</tocitem>\n');
    end
    fprintf(fid,'</tocitem>\n');
    fprintf(fid,'\n</toc>\n');
    fclose(fid);
end
%--------------------------------------------------------------------------
%- Write an index for each output directory
%--------------------------------------------------------------------------
tpl_mdir = 'mdir.tpl';
tpl_mdir_link = '<a href="%s">%s</a>';
%dotbase defined earlier
%- Create the HTML template
tpl = template(options.template,'remove');
tpl = set(tpl,'file','TPL_MDIR',tpl_mdir);
tpl = set(tpl,'block','TPL_MDIR','row-m','rows-m');
tpl = set(tpl,'block','row-m','mexfile','mex');
tpl = set(tpl,'block','TPL_MDIR','othermatlab','other');
tpl = set(tpl,'block','othermatlab','row-other','rows-other');
tpl = set(tpl,'block','TPL_MDIR','subfolder','subfold');
tpl = set(tpl,'block','subfolder','subdir','subdirs');
tpl = set(tpl,'block','TPL_MDIR','todolist','todolists');
tpl = set(tpl,'block','TPL_MDIR','graph','graphs');
tpl = set(tpl,'var','DATE',[datestr(now,8) ' ' datestr(now,1) ' ' ...
                            datestr(now,13)]);
for i=1:length(mdir)
    %- Open for writing each output directory index file
    curfile = fullfile(options.htmlDir,mdir{i},...
                       [options.indexFile options.extension]);
    if options.verbose
        fprintf('Creating HTML file %s...\n',curfile);
    end
    fid = openfile(curfile,'w');
    %- Set template fields
    tpl = set(tpl,'var','INDEX',     [options.indexFile options.extension]);
    tpl = set(tpl,'var','MASTERPATH',backtomaster(mdir{i}));
    tpl = set(tpl,'var','MDIR',      mdir{i});
    %- Display Matlab m-files, their H1 line and their Mex status
    tpl = set(tpl,'var','rows-m','');
    for j=1:length(mdirs)
        if strcmp(mdirs{j},mdir{i})
            tpl = set(tpl,'var','L_NAME', [names{j} options.extension]);
            tpl = set(tpl,'var','NAME',   names{j});
            tpl = set(tpl,'var','H1LINE', h1line{j});
            if any(ismex(j,:))
                tpl = parse(tpl,'mex','mexfile');
            else
                tpl = set(tpl,'var','mex','');
            end
            tpl = parse(tpl,'rows-m','row-m',1);
        end
    end
    %- Display other Matlab-specific files (.mat,.mdl,.p)
    tpl = set(tpl,'var','other','');
    tpl = set(tpl,'var','rows-other','');
    w = what(mdir{i}); w = w(1);
    w = {w.mat{:} w.mdl{:} w.p{:}};
    for j=1:length(w)
        tpl = set(tpl,'var','OTHERFILE',w{j});
        tpl = parse(tpl,'rows-other','row-other',1);
    end
    if ~isempty(w)
        tpl = parse(tpl,'other','othermatlab');
    end
    %- Display subsequent directories and classes
    tpl = set(tpl,'var','subdirs','');
    tpl = set(tpl,'var','subfold','');
    d = dir(mdir{i});
    d = {d([d.isdir]).name};
    d = {d{~ismember(d,{'.' '..' options.ignoredDir{:}})}};
    for j=1:length(d)
        if ismember(fullfile(mdir{i},d{j}),mdir)
            tpl = set(tpl,'var','SUBDIRECTORY',...
                sprintf(tpl_mdir_link,...
                fullurl(d{j},[options.indexFile options.extension]),d{j}));
        else
            tpl = set(tpl,'var','SUBDIRECTORY',d{j});
        end
        tpl = parse(tpl,'subdirs','subdir',1);
    end
    if ~isempty(d)
        tpl = parse(tpl,'subfold','subfolder');
    end
    %- Link to the TODO list if necessary
    tpl = set(tpl,'var','todolists','');
    if options.todo
        if ~isempty(intersect(find(strcmp(mdir{i},mdirs)),todo.mfile))
            tpl = set(tpl,'var','LTODOLIST',['todo' options.extension]);
            tpl = parse(tpl,'todolists','todolist',1);
        end
    end
    %- Link to the dependency graph if necessary
    tpl = set(tpl,'var','graphs','');
    if options.graph
        tpl = set(tpl,'var','LGRAPH',[dotbase options.extension]);
        tpl = parse(tpl,'graphs','graph',1);
    end
    %- Print the template in the HTML file
    tpl = parse(tpl,'OUT','TPL_MDIR');
    fprintf(fid,'%s',get(tpl,'OUT'));
    fclose(fid);
end
%--------------------------------------------------------------------------
%- Write a TODO list file for each output directory, if necessary
%--------------------------------------------------------------------------
tpl_todo = 'todo.tpl';
if options.todo
    %- Create the HTML template
    tpl = template(options.template,'remove');
    tpl = set(tpl,'file','TPL_TODO',tpl_todo);
    tpl = set(tpl,'block','TPL_TODO','filelist','filelists');
    tpl = set(tpl,'block','filelist','row','rows');
    tpl = set(tpl,'var','DATE',[datestr(now,8) ' ' datestr(now,1) ' ' ...
                                datestr(now,13)]);
    for i=1:length(mdir)
        mfilestodo = intersect(find(strcmp(mdir{i},mdirs)),todo.mfile);
        if ~isempty(mfilestodo)
            %- Open for writing each TODO list file
            curfile = fullfile(options.htmlDir,mdir{i},...
                               ['todo' options.extension]);
            if options.verbose
                fprintf('Creating HTML file %s...\n',curfile);
            end
            fid = openfile(curfile,'w');
            %- Set template fields
            tpl = set(tpl,'var','INDEX',[options.indexFile options.extension]);
            tpl = set(tpl,'var','MASTERPATH', backtomaster(mdir{i}));
            tpl = set(tpl,'var','MDIR',       mdir{i});
            tpl = set(tpl,'var','filelists',  '');
            for k=1:length(mfilestodo)
                tpl = set(tpl,'var','MFILE',names{mfilestodo(k)});
                tpl = set(tpl,'var','rows','');
                nbtodo = find(todo.mfile == mfilestodo(k));
                for l=1:length(nbtodo)
                    tpl = set(tpl,'var','L_NBLINE',...
                        [names{mfilestodo(k)} ...
                            options.extension ...
                            '#l' num2str(todo.line(nbtodo(l)))]);
                    tpl = set(tpl,'var','NBLINE',num2str(todo.line(nbtodo(l))));
                    tpl = set(tpl,'var','COMMENT',todo.comment{nbtodo(l)});
                    tpl = parse(tpl,'rows','row',1);
                end
                tpl = parse(tpl,'filelists','filelist',1);
            end
            %- Print the template in the HTML file
            tpl = parse(tpl,'OUT','TPL_TODO');
            fprintf(fid,'%s',get(tpl,'OUT'));
            fclose(fid);
        end
    end
end
%--------------------------------------------------------------------------
%- Create dependency graphs using GraphViz, if requested
%--------------------------------------------------------------------------
tpl_graph = 'graph.tpl';
% You may have to modify the following line with Matlab7 (R14) to specify
% the full path to where GraphViz is installed
dot_exec  = 'dot';
%dotbase defined earlier
if options.graph
    %- Create the HTML template
    tpl = template(options.template,'remove');
    tpl = set(tpl,'file','TPL_GRAPH',tpl_graph);
    tpl = set(tpl,'var','DATE',[datestr(now,8) ' ' datestr(now,1) ' ' ...
                                datestr(now,13)]);
    %- Create a full dependency graph for all directories if possible
    if options.globalHypertextLinks && length(mdir) > 1
        mdotfile = fullfile(options.htmlDir,[dotbase '.dot']);
        if options.verbose
            fprintf('Creating full dependency graph %s...',mdotfile);
        end
        mdot({hrefs, names, options, mdirs}, mdotfile); %mfiles
        calldot(dot_exec, mdotfile, ...
                fullfile(options.htmlDir,[dotbase '.map']), ...
                fullfile(options.htmlDir,[dotbase '.png']));
        if options.verbose, fprintf('\n'); end
        fid = openfile(fullfile(options.htmlDir, [dotbase options.extension]),'w');
        tpl = set(tpl,'var','INDEX',[options.indexFile options.extension]);
        tpl = set(tpl,'var','MASTERPATH', './');
        tpl = set(tpl,'var','MDIR',       'the whole toolbox');
        tpl = set(tpl,'var','GRAPH_IMG',  [dotbase '.png']);
        try % if <dot> failed...
            fmap = openfile(fullfile(options.htmlDir,[dotbase '.map']),'r');
            tpl = set(tpl,'var','GRAPH_MAP',  fscanf(fmap,'%c'));
            fclose(fmap);
        end
        tpl = parse(tpl,'OUT','TPL_GRAPH');
        fprintf(fid,'%s', get(tpl,'OUT'));
        fclose(fid);
    end
    %- Create a dependency graph for each output directory
    for i=1:length(mdir)
        mdotfile = fullfile(options.htmlDir,mdir{i},[dotbase '.dot']);
        if options.verbose
            fprintf('Creating dependency graph %s...',mdotfile);
        end
        ind = find(strcmp(mdirs,mdir{i}));
        href1 = zeros(length(ind),length(hrefs));
        for j=1:length(hrefs), href1(:,j) = hrefs(ind,j); end
        href2 = zeros(length(ind));
        for j=1:length(ind), href2(j,:) = href1(j,ind); end
        mdot({href2, {names{ind}}, options}, mdotfile); %{mfiles{ind}}
        calldot(dot_exec, mdotfile, ...
                fullfile(options.htmlDir,mdir{i},[dotbase '.map']), ...
                fullfile(options.htmlDir,mdir{i},[dotbase '.png']));
        if options.verbose, fprintf('\n'); end
        fid = openfile(fullfile(options.htmlDir,mdir{i},...
            [dotbase options.extension]),'w');
        tpl = set(tpl,'var','INDEX',[options.indexFile options.extension]);
        tpl = set(tpl,'var','MASTERPATH', backtomaster(mdir{i}));
        tpl = set(tpl,'var','MDIR',       mdir{i});
        tpl = set(tpl,'var','GRAPH_IMG',  [dotbase '.png']);
        try % if <dot> failed, no '.map' file has been created
            fmap = openfile(fullfile(options.htmlDir,mdir{i},[dotbase '.map']),'r');
            tpl = set(tpl,'var','GRAPH_MAP',  fscanf(fmap,'%c'));
            fclose(fmap);
        end
        tpl = parse(tpl,'OUT','TPL_GRAPH');
        fprintf(fid,'%s', get(tpl,'OUT'));
        fclose(fid);
    end
end
%--------------------------------------------------------------------------
%- Write an HTML file for each M-file
%--------------------------------------------------------------------------
%- List of Matlab keywords (output from iskeyword)
matlabKeywords = {'break', 'case', 'catch', 'continue', 'elseif', 'else', ...
                  'end', 'for', 'function', 'global', 'if', 'otherwise', ...
                  'persistent', 'return', 'switch', 'try', 'while'};
                  %'keyboard', 'pause', 'eps', 'NaN', 'Inf'
tpl_mfile = 'mfile.tpl';
tpl_mfile_code     = '<a href="%s" class="code" title="%s">%s</a>';
tpl_mfile_keyword  = '<span class="keyword">%s</span>';
tpl_mfile_comment  = '<span class="comment">%s</span>';
tpl_mfile_string   = '<span class="string">%s</span>';
tpl_mfile_aname    = '<a name="%s" href="#_subfunctions" class="code">%s</a>';
tpl_mfile_line     = '%04d %s\n';
%- Delimiters used in strtok: some of them may be useless (% " .), removed '.'
strtok_delim = sprintf(' \t\n\r(){}[]<>+-*~!|\\@&/,:;="''%%');
%- Create the HTML template
tpl = template(options.template,'remove');
tpl = set(tpl,'file','TPL_MFILE',tpl_mfile);
tpl = set(tpl,'block','TPL_MFILE','pathline','pl');
tpl = set(tpl,'block','TPL_MFILE','mexfile','mex');
tpl = set(tpl,'block','TPL_MFILE','script','scriptfile');
tpl = set(tpl,'block','TPL_MFILE','crossrefcall','crossrefcalls');
tpl = set(tpl,'block','TPL_MFILE','crossrefcalled','crossrefcalleds');
tpl = set(tpl,'block','TPL_MFILE','subfunction','subf');
tpl = set(tpl,'block','subfunction','onesubfunction','onesubf');
tpl = set(tpl,'block','TPL_MFILE','source','thesource');
tpl = set(tpl,'block','TPL_MFILE','download','downloads');
tpl = set(tpl,'var','DATE',[datestr(now,8) ' ' datestr(now,1) ' ' ...
                            datestr(now,13)]);
nblinetot = 0;
for i=1:length(mdir)
    for j=1:length(mdirs)
        if strcmp(mdirs{j},mdir{i})
            curfile = fullfile(options.htmlDir,mdir{i},...
                               [names{j} options.extension]);
            %- Copy M-file for download, if necessary
            if options.download
                if options.verbose
                    fprintf('Copying M-file %s.m to %s...\n',names{j},...
                        fullfile(options.htmlDir,mdir{i}));
                end
                [status, errmsg] = copyfile(mfiles{j},...
                    fullfile(options.htmlDir,mdir{i}));
                error(errmsg);
            end
            %- Open for writing the HTML file
            if options.verbose
                fprintf('Creating HTML file %s...\n',curfile);
            end
1000             fid = openfile(curfile,'w');
1001             if strcmp(names{j},options.indexFile)
1002                 fprintf(['Warning: HTML index file %s will be ' ...
1003                         'overwritten by Matlab function %s.\n'], ...
1004                         [options.indexFile options.extension], mfiles{j});
1005             end
1006
1007             %- Open for reading the M-file
1008             fid2 = openfile(mfiles{j},'r');
1009
1010             %- Set some template fields
1011             tpl = set(tpl,'var','INDEX', [options.indexFile options.extension]);
1012             tpl = set(tpl,'var','MASTERPATH',       backtomaster(mdir{i}));
1013             tpl = set(tpl,'var','MDIR',             mdirs{j});
1014             tpl = set(tpl,'var','NAME',             names{j});
1015             tpl = set(tpl,'var','H1LINE',           entity(h1line{j}));
1016             tpl = set(tpl,'var','scriptfile',       '');
1017             if isempty(synopsis{j})
1018                 tpl = set(tpl,'var','SYNOPSIS',get(tpl,'var','script'));
1019             else
1020                 tpl = set(tpl,'var','SYNOPSIS', synopsis{j});
1021             end
1022             s = splitpath(mdir{i});
1023             tpl = set(tpl,'var','pl','');
1024             for k=1:length(s)
1025                 c = cell(1,k); for l=1:k, c{l} = filesep; end
1026                 cpath = {s{1:k};c{:}}; cpath = [cpath{:}];
1027                 if ~isempty(cpath), cpath = cpath(1:end-1); end
1028                 if ismember(cpath,mdir)
1029                     tpl = set(tpl,'var','LPATHDIR',[repmat('../',...
1030                         1,length(s)-k) options.indexFile options.extension]);
1031                 else
1032                     tpl = set(tpl,'var','LPATHDIR','#');
1033                 end
1034                 tpl = set(tpl,'var','PATHDIR',s{k});
1035                 tpl = parse(tpl,'pl','pathline',1);
1036             end
1037
1038             %- Handle mex files
1039             tpl = set(tpl,'var','mex', '');
1040             samename = dir(fullfile(mdir{i},[names{j}    '.*']));
1041             samename = {samename.name};
1042             tpl = set(tpl,'var','MEXTYPE', 'mex');
1043             for k=1:length(samename)
1044                 [dummy, dummy, ext] = fileparts(samename{k});
1045                 switch ext
1046                     case '.c'
1047                         tpl = set(tpl,'var','MEXTYPE', 'c');
1048                     case {'.cpp' '.c++' '.cxx' '.C'}
1049                         tpl = set(tpl,'var','MEXTYPE', 'c++');
1050                     case {'.for' '.f' '.FOR' '.F'}
1051                         tpl = set(tpl,'var','MEXTYPE', 'fortran');
1052                     otherwise
1053                         %- Unknown mex file source
1054                 end
1055             end
1056             allexts = mexexts;
1057             platform = {allexts.arch};
1058             mexplatforms = sprintf('%s, ',platform{find(ismex(j,:))});
1059             if ~isempty(mexplatforms)
1060                 tpl = set(tpl,'var','PLATFORMS', mexplatforms(1:end-2));
1061                 tpl = parse(tpl,'mex','mexfile');
1062             end
1063
1064             %- Set description template field
1065             descr = '';
1066             flagsynopcont = 0;
1067             flag_seealso  = 0;
1068             while 1
1069                 tline = fgets(fid2);
1070                 if ~ischar(tline), break, end
1071                 tline = entity(fliplr(deblank(fliplr(tline))));
1072                 %- Synopsis line
1073                 if ~isempty(strmatch('function',tline))
1074                     if ~isempty(strmatch('...',fliplr(deblank(tline))))
1075                         flagsynopcont = 1;
1076                     end
1077                 %- H1 line and description
1078                 elseif ~isempty(strmatch('%',tline))
1079                     %- Hypertext links on the "See also" line
1080                     ind = findstr(lower(tline),'see also');
1081                     if ~isempty(ind) || flag_seealso
1082                         %- "See also" only in files in the same directory
1083                         indsamedir = find(strcmp(mdirs{j},mdirs));
1084                         hrefnames = {names{indsamedir}};
1085                         r = deblank(tline);
1086                         flag_seealso = 1; %(r(end) == ',');
1087                         tline = '';
1088                         while 1
1089                             [t,r,q] = strtok2(r,sprintf(' \t\n\r.,;%%'));
1090                             tline = [tline q];
1091                             if isempty(t), break, end
1092                             ii = strcmpi(hrefnames,t);
1093                             if any(ii)
1094                                 jj = find(ii);
1095                                 tline = [tline sprintf(tpl_mfile_code,...
1096                                     [hrefnames{jj(1)} options.extension],...
1097                                     synopsis{indsamedir(jj(1))},t)];
1098                             else
1099                                 tline = [tline t];
1100                             end
1101                         end
1102                         tline = sprintf('%s\n',tline);
1103                     end
1104                     descr = [descr tline(2:end)];
1105                 elseif isempty(tline)
1106                     if ~isempty(descr), break, end
1107                 else
1108                     if flagsynopcont
1109                         if isempty(strmatch('...',fliplr(deblank(tline))))
1110                             flagsynopcont = 0;
1111                         end
1112                     else
1113                         break;
1114                     end
1115                 end
1116             end
1117             tpl = set(tpl,'var','DESCRIPTION',...
1118                 horztab(descr,options.tabs));
1119
1120             %- Set cross-references template fields:
1121             %  Function called
1122             ind = find(hrefs(j,:) == 1);
1123             tpl = set(tpl,'var','crossrefcalls','');
1124             for k=1:length(ind)
1125                 if strcmp(mdirs{j},mdirs{ind(k)})
1126                     tpl = set(tpl,'var','L_NAME_CALL', ...
1127                         [names{ind(k)} options.extension]);
1128                 else
1129                     tpl = set(tpl,'var','L_NAME_CALL', ...
1130                               fullurl(backtomaster(mdirs{j}), ...
1131                                          mdirs{ind(k)}, ...
1132                                        [names{ind(k)} options.extension]));
1133                 end
1134                 tpl = set(tpl,'var','SYNOP_CALL',   synopsis{ind(k)});
1135                 tpl = set(tpl,'var','NAME_CALL',   names{ind(k)});
1136                 tpl = set(tpl,'var','H1LINE_CALL', h1line{ind(k)});
1137                 tpl = parse(tpl,'crossrefcalls','crossrefcall',1);
1138             end
1139             %  Callers
1140             ind = find(hrefs(:,j) == 1);
1141             tpl = set(tpl,'var','crossrefcalleds','');
1142             for k=1:length(ind)
1143                 if strcmp(mdirs{j},mdirs{ind(k)})
1144                     tpl = set(tpl,'var','L_NAME_CALLED', ...
1145                         [names{ind(k)} options.extension]);
1146                 else
1147                     tpl = set(tpl,'var','L_NAME_CALLED', ...
1148                         fullurl(backtomaster(mdirs{j}),...
1149                             mdirs{ind(k)}, ...
1150                             [names{ind(k)} options.extension]));
1151                 end
1152                 tpl = set(tpl,'var','SYNOP_CALLED',   synopsis{ind(k)});
1153                 tpl = set(tpl,'var','NAME_CALLED',   names{ind(k)});
1154                 tpl = set(tpl,'var','H1LINE_CALLED', h1line{ind(k)});
1155                 tpl = parse(tpl,'crossrefcalleds','crossrefcalled',1);
1156             end
1157
1158             %- Set subfunction template field
1159             tpl = set(tpl,'var',{'subf' 'onesubf'},{'' ''});
1160             if ~isempty(subroutine{j}) && options.source
1161                 for k=1:length(subroutine{j})
1162                     tpl = set(tpl, 'var', 'L_SUB', ['#_sub' num2str(k)]);
1163                     tpl = set(tpl, 'var', 'SUB',   subroutine{j}{k});
1164                     tpl = parse(tpl, 'onesubf', 'onesubfunction',1);
1165                 end
1166                 tpl = parse(tpl,'subf','subfunction');
1167             end
1168             subname = extractname(subroutine{j});
1169
1170             %- Link to M-file (for download)
1171             tpl = set(tpl,'var','downloads','');
1172             if options.download
1173                 tpl = parse(tpl,'downloads','download',1);
1174             end
1175
1176             %- Display source code with cross-references
1177             if options.source && ~strcmpi(names{j},'contents')
1178                 fseek(fid2,0,-1);
1179                 it = 1;
1180                 matlabsource = '';
1181                 nbsubroutine = 1;
1182                 %- Get href function names of this file
1183                 indhrefnames = find(hrefs(j,:) == 1);
1184                 hrefnames = {names{indhrefnames}};
1185                 %- Loop over lines
1186                 while 1
1187                     tline = fgetl(fid2);
1188                     if ~ischar(tline), break, end
1189                     myline = '';
1190                     splitc = splitcode(entity(tline));
1191                     for k=1:length(splitc)
1192                         if isempty(splitc{k})
1193                         elseif ~isempty(strmatch('function', ...
1194                                         fliplr(deblank(fliplr(splitc{k})))))
1195                             if isspace(splitc{k}(1))
1196                                 nbs = find(diff(isspace(splitc{k}))==-1);
1197                                 myline = [myline splitc{k}(1:nbs(1))];
1198                                 splitc{k} = splitc{k}(nbs(1)+1:end);
1199                             end
1200                             %- Subfunctions definition
1201                             myline = [myline ...
1202                                 sprintf(tpl_mfile_aname,...
1203                                     ['_sub' num2str(nbsubroutine-1)],splitc{k})];
1204                             nbsubroutine = nbsubroutine + 1;
1205                         elseif splitc{k}(1) == ''''
1206                             myline = [myline ...
1207                                 sprintf(tpl_mfile_string,splitc{k})];
1208                         elseif splitc{k}(1) == '%'
1209                             myline = [myline ...
1210                                 sprintf(tpl_mfile_comment,deblank(splitc{k}))];
1211                         elseif ~isempty(strmatch('...',splitc{k}))
1212                             myline = [myline sprintf(tpl_mfile_keyword,'...')];
1213                             if ~isempty(splitc{k}(4:end))
1214                                 myline = [myline ...
1215                                     sprintf(tpl_mfile_comment,splitc{k}(4:end))];
1216                             end
1217                         else
1218                             %- Look for keywords
1219                             r = splitc{k};
1220                             while 1
1221                                 [t,r,q] = strtok2(r,strtok_delim);
1222                                 myline = [myline q];
1223                                 if isempty(t), break, end
1224                                 %- Highlight Matlab keywords &
1225                                 %  cross-references on known functions
1226                                 if options.syntaxHighlighting && ...
1227                                         any(strcmp(matlabKeywords,t))
1228                                     if strcmp('end',t)
1229                                         rr = fliplr(deblank(fliplr(r)));
1230                                         icomma = strmatch(',',rr);
1231                                         isemicolon = strmatch(';',rr);
1232                                         if ~(isempty(rr) || ~isempty([icomma isemicolon]))
1233                                             myline = [myline t];
1234                                         else
1235                                             myline = [myline sprintf(tpl_mfile_keyword,t)];
1236                                         end
1237                                     else
1238                                         myline = [myline sprintf(tpl_mfile_keyword,t)];
1239                                     end
1240                                 elseif any(strcmp(hrefnames,t))
1241                                     indt = indhrefnames(logical(strcmp(hrefnames,t)));
1242                                     flink = [t options.extension];
1243                                     ii = ismember({mdirs{indt}},mdirs{j});
1244                                     if ~any(ii)
1245                                         % take the first one...
1246                                         flink = fullurl(backtomaster(mdirs{j}),...
1247                                                           mdirs{indt(1)}, flink);
1248                                     else
1249                                         indt = indt(logical(ii));
1250                                     end
1251                                     myline = [myline sprintf(tpl_mfile_code,...
1252                                               flink, synopsis{indt(1)}, t)];
1253                                 elseif any(strcmp(subname,t))
1254                                     ii = find(strcmp(subname,t));
1255                                     myline = [myline sprintf(tpl_mfile_code,...
1256                                         ['#_sub' num2str(ii)],...
1257                                         ['sub' subroutine{j}{ii}],t)];
1258                                 else
1259                                     myline = [myline t];
1260                                 end
1261                             end
1262                         end
1263                     end
1264                     matlabsource = [matlabsource sprintf(tpl_mfile_line,it,myline)];
1265                     it = it + 1;
1266                 end
1267                 nblinetot = nblinetot + it - 1;
1268                 tpl = set(tpl,'var','SOURCECODE',...
1269                           horztab(matlabsource,options.tabs));
1270                 tpl = parse(tpl,'thesource','source');
1271             else
1272                 tpl = set(tpl,'var','thesource','');
1273             end
1274             tpl = parse(tpl,'OUT','TPL_MFILE');
1275             fprintf(fid,'%s',get(tpl,'OUT'));
1276             fclose(fid2);
1277             fclose(fid);
1278         end
1279     end
1280 end
1281
1282 %--------------------------------------------------------------------------
1283 %- Display Statistics
1284 %--------------------------------------------------------------------------
1285 if options.verbose
1286     prnbline = '';
1287     if options.source
1288         prnbline = sprintf('(%d lines) ', nblinetot);
1289     end
1290     fprintf('Stats: %d M-files %sin %d directories documented in %d s.\n', ...
1291             length(mfiles), prnbline, length(mdir), round(etime(clock,t0)));
1292 end
1293
1294 %==========================================================================
1295 function mfiles = getmfiles(mdirs, mfiles, recursive,ignoredDir)
1296     %- Extract M-files from a list of directories and/or M-files
1297
1298     if nargin < 4, ignoredDir = {}; end
1299     for i=1:length(mdirs)
1300         currentdir = fullfile(pwd, mdirs{i});
1301         if exist(currentdir) == 2 % M-file
1302             mfiles{end+1} = mdirs{i};
1303         elseif exist(currentdir) == 7 % Directory
1304             d = dir(fullfile(currentdir, '*.m'));
1305             d = {d(~[d.isdir]).name};
1306             for j=1:length(d)
1307                 %- don't take care of files containing ','
1308                 %  probably a sccs file...
1309                 if isempty(findstr(',',d{j}))
1310                     mfiles{end+1} = fullfile(mdirs{i}, d{j});
1311                 end
1312             end
1313             if recursive
1314                 d = dir(currentdir);
1315                 d = {d([d.isdir]).name};
1316                 d = {d{~ismember(d,{'.' '..' ignoredDir{:}})}};
1317                 for j=1:length(d)
1318                     mfiles = getmfiles(cellstr(fullfile(mdirs{i},d{j})), ...
1319                                        mfiles, recursive);
1320                 end
1321             end
1322         else
1323             fprintf('Warning: Unprocessed file %s.\n',mdirs{i});
1324             if ~isempty(strmatch('/',mdirs{i})) || findstr(':',mdirs{i})
1325                 fprintf('         Use relative paths in ''mfiles'' option\n');
1326             end
1327         end
1328     end
1329
1330 %==========================================================================
1331 function calldot(dotexec, mdotfile, mapfile, pngfile, opt)
1332     %- Draw a dependency graph in a PNG image using <dot> from GraphViz
1333
1334     if nargin == 4, opt = ''; end
1335     try
1336         %- See <http://www.graphviz.org/>
1337         %  <dot> must be in your system path, see M2HTML FAQ:
1338         %  <http://www.artefact.tk/software/matlab/m2html/faq.php>
1339
1340         system(['"' dotexec '" ' opt ' -Tcmap -Tpng "' mdotfile ...
1341               '" -o "' mapfile ...
1342               '" -o "' pngfile '"']);
1343     catch % use of '!' prevents errors to be catched...
1344         fprintf('<dot> failed.');
1345     end
1346
1347 %==========================================================================
1348 function s = backtomaster(mdir)
1349     %- Provide filesystem path to go back to the root folder
1350
1351     ldir = splitpath(mdir);
1352     s = repmat('../',1,length(ldir));
1353
1354 %==========================================================================
1355 function ldir = splitpath(p)
1356     %- Split a filesystem path into parts using filesep as separator
1357
1358     ldir = {};
1359     p = deblank(p);
1360     while 1
1361         [t,p] = strtok(p,filesep);
1362         if isempty(t), break; end
1363         if ~strcmp(t,'.')
1364             ldir{end+1} = t;
1365         end
1366     end
1367     if isempty(ldir)
1368         ldir{1} = '.'; % should be removed
1369     end
1370
1371 %==========================================================================
1372 function name = extractname(synopsis)
1373     %- Extract function name in a synopsis
1374
1375     if ischar(synopsis), synopsis = {synopsis}; end
1376     name = cell(size(synopsis));
1377     for i=1:length(synopsis)
1378         ind = findstr(synopsis{i},'=');
1379         if isempty(ind)
1380             ind = findstr(synopsis{i},'function');
1381             s = synopsis{i}(ind(1)+8:end);
1382         else
1383             s = synopsis{i}(ind(1)+1:end);
1384         end
1385         name{i} = strtok(s,[9:13 32 40]); % white space characters and '('
1386     end
1387     if length(name) == 1, name = name{1}; end
1388
1389 %==========================================================================
1390 function f = fullurl(varargin)
1391     %- Build full url from parts (using '/' and not filesep)
1392
1393     f = strrep(fullfile(varargin{:}),'\','/');
1394
1395 %==========================================================================
1396 function str = escapeblank(str)
1397     %- Escape white spaces using '\'
1398
1399     str = deblank(fliplr(deblank(fliplr(str))));
1400     %str = strrep(str,' ','\ ');
1401
1402 %==========================================================================
1403 function str = entity(str)
1404     %- Escape HTML special characters
1405     %- See http://www.w3.org/TR/html4/charset.html#h-5.3.2
1406
1407     str = strrep(str,'&','&amp;');
1408     str = strrep(str,'<','&lt;');
1409     str = strrep(str,'>','&gt;');
1410     str = strrep(str,'"','&quot;');
1411
1412 %==========================================================================
1413 function str = horztab(str,n)
1414     %- For browsers, the horizontal tab character is the smallest non-zero
1415     %- number of spaces necessary to line characters up along tab stops that are
1416     %- every 8 characters: behaviour obtained when n = 0.
1417
1418     if n > 0
1419         str = strrep(str,sprintf('\t'),blanks(n));
1420     end